import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F6F6F6",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F6F6F6",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#2E7D32",
    fontWeight: "500",
  },
  logoWrapper: {
    overflow: "hidden",
    height: 200,
  },
  logoContainer: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  blurView: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  logo: {
    width: 150,
    height: 150,
    resizeMode: "contain",
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  formWrapper: {
    backgroundColor: "#fff",
    margin: 15,
    padding: 20,
    paddingVertical: 25,
    borderRadius: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    maxHeight: "150%",
    borderWidth: 1,
    borderColor: "#E0F2E9",
  },
  title: {
    textAlign: "center",
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#2E7D32",
    textTransform: "uppercase",
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 25,
    backgroundColor: "#F5F5F5",
    borderRadius: 15,
    padding: 2,
  },
  tabButton: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    marginHorizontal: 5,
    borderRadius: 12,
    backgroundColor: "#E8F5E9",
  },
  activeTab: {
    backgroundColor: "#2E7D32",
  },
  tabText: {
    fontSize: 15,
    color: "#666",
    fontWeight: "500",
  },
  activeTabText: {
    color: "#fff",
    fontWeight: "bold",
  },
  input: {
    height: 50,
    backgroundColor: "#E8F5E9",
    borderRadius: 12,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#C8E6C9",
    marginBottom: 15,
    fontSize: 16,
    color: "#333",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  forgotPassword: {
    textAlign: "left",
    color: "#388E3C",
    fontSize: 13,
    marginBottom: 15,
    textDecorationLine: "underline",
  },
  error: {
    color: "#D32F2F",
    textAlign: "center",
    marginBottom: 15,
    fontSize: 14,
  },
  loginButton: {
    backgroundColor: "#2E7D32",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 15,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  loginButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
  },
  googleButton: {
    backgroundColor: "#fff",
    borderColor: "#C8E6C9",
    borderWidth: 1,
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 15,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    elevation: 2,
  },
  googleContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  gog: {
    width: 22,
    height: 22,
    resizeMode: "contain",
    marginRight: 12,
  },
  googleButtonText: {
    color: "#424242",
    fontSize: 16,
  },
  qrButton: {
    backgroundColor: "#fff",
    borderColor: "#C8E6C9",
    borderWidth: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 20,
    elevation: 2,
  },
  qrButtonText: {
    color: "#388E3C",
    fontSize: 16,
  },
  privacyText: {
    textAlign: "center",
    color: "#757575",
    fontSize: 13,
    marginTop: 10,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    width: "80%",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
    color: "#2E7D32",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },
  cancelButton: {
    marginTop: 10,
    padding: 10,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#E53935",
  },
});

export default styles;
